server:
  port: 9090
  servlet:
    context-path: /stock
  tomcat:
    uri-encoding: UTF-8

spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    include: db
    active: db
  output:
    ansi:
      enabled: detect
  application:
    name: tx-msg-order
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true


