spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 5
      max-wait: 60000
      time-between-eviction-runs-millis: 3600000
      min-evictable-idle-time-millis: 3600000
      validation-query: select 1 from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: true
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 5
      max-open-prepared-statements: 5
      filters: stat

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      table-underline: true
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    jdbc-type-for-null: 'null'
  mapper-locations: class*:/mapper/*.xml
  type-aliases-package: com.dmai.transaction.order.entity.*
rocketmq:
  name-server: 10.32.1.100:9876
  producer:
    group: order-group
    send-message-timeout: 6000